version: '3.8'

services:

  nats:
    image: nats:latest
    container_name: NATS
    ports:
      - "4222:4222"
    expose:
      - "4222"

  user_server:
    build:
      context: ./user_server
    container_name: user_server
    environment:
      - US_DATABASE_URL=database_server
      - US_USER=admin
      - US_PASSWORD=12345
      - US_DBNAME=users_db
      - US_PORT=5432
      - US_NATS_SERVER=nats
    depends_on:
      - database_server
      - nats
    ports:
      - "8080:8080"
      

  logs_server:
    build:
      context: ./logs_server
    container_name: logs_server
    environment:
      - LS_DATABASE_URL=database_server
      - LS_USER=admin
      - LS_PASSWORD=12345
      - LS_DBNAME=logs_db
      - LS_PORT=5432
      - LS_NATS_SERVER=nats
    depends_on:
      - user_server
      - database_server
      - nats
    ports:
      - "8081:8081"

  # user_database:
  #   build:
  #     context: ./user_database
  #   container_name: user_database
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"
      
  database_server:
    build:
      context: ./database_server
    container_name: database_server
    ports:
      - "5432:5432"

  # jenkins:
  #   image: jenkins/jenkins:lts
  #   ports:
  #     - "6432:8080"
  #     - "50000:50000"

  #Levanta el composer con docker-compose up --build
